#!/bin/sh
#
# Start the preinit
#

MNTDIR=""
wait_for_media_ready()
{
	while true
	do
		for subdir in $(ls /media); do
			if [ -e /media/$subdir/cubegm/icube ] ; then
				MNTDIR=$subdir
				return
			fi
		done

		sleep 0.5
	done
}

wait_for_media_ready

#mount
echo "mount --bind /media/${MNTDIR} /mnt/sdcard"
mount --bind /media/${MNTDIR} /mnt/sdcard
memsize=$(free | grep Mem | awk '{print $2}')

if [ -d /media/${MNTDIR}/rootfs ] ; then
	echo "mount --bind /media/${MNTDIR}/rootfs/lib /lib"
	mount --bind /media/${MNTDIR}/rootfs/lib /lib
	echo "mount --bind /media/${MNTDIR}/rootfs/usr /usr"
	mount --bind /media/${MNTDIR}/rootfs/usr /usr
	echo "mount --bind /media/${MNTDIR}/rootfs/bin /bin"
	mount --bind /media/${MNTDIR}/rootfs/bin /bin
	echo "mount --bind /media/${MNTDIR}/rootfs/sbin /sbin"
	mount --bind /media/${MNTDIR}/rootfs/sbin /sbin
	echo "mount --bind /media/${MNTDIR}/rootfs/etc /etc"
	mount --bind /media/${MNTDIR}/rootfs/etc /etc
	echo "mount --bind /media/${MNTDIR}/rootfs/hcdemo_files /hcdemo_files"
	mount --bind /media/${MNTDIR}/rootfs/hcdemo_files /hcdemo_files
else
	mount --bind /media/${MNTDIR}/cubegm/lib /lib
	echo "mount --bind /media/${MNTDIR}/cubegm/lib /lib"
	mount --bind /media/${MNTDIR}/cubegm/usr/lib /usr/lib
	echo "mount --bind /media/${MNTDIR}/cubegm/usr/lib /usr/lib"
fi

if [ $memsize -le 128000 ] ; then
	if [ ! -f /mnt/sdcard/cubegm/pagefile.sys ] ; then
		echo "Not found pagefile.sys, rebooting ..."
		echo "Creating pagefile.sys ..."
		fallocate -l 128M /mnt/sdcard/cubegm/pagefile.sys
		mkswap /mnt/sdcard/cubegm/pagefile.sys
		echo "Creating pagefile.sys done"
	fi
	if [ -f /mnt/sdcard/cubegm/pagefile.sys ] ; then
		echo "Swapon ..."
		swapon /mnt/sdcard/cubegm/pagefile.sys
		if [ $? -eq 0 ] && [ $(free | grep Swap | awk '{print $2}') -gt 0 ]; then
			echo "Swap space activated successfully"
			/mnt/sdcard/cubegm/icube.sh &
		else
			echo "Failed to activate swap space"
			# You can add error handling here if needed
		fi
	fi
else
/mnt/sdcard/cubegm/icube.sh &
fi
